### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by ihorsniezhko** [ihorsniezhko/project-planning-demo#1]
**User Story**

"As a potential client, I want to read testimonials from previous clients so that I can trust the photographer's service."

**Acceptance Criteria:**

- [ ] - The testimonials page displays at least five client testimonials.
- [ ] - Each testimonial includes the client's first name, year of wedding, and comments.
- [ ] - The testimonials section is responsive and looks good on multiple device sizes.

**Tasks:**

- [ ] - Create an HTML section for testimonials.
- [ ] - Style the testimonials section using CSS and Bootstrap.
- [ ] - Use Bootstrap's grid system to make sure the testimonials section is responsive.
